# Interactive Finite Element Analysis (FEA) - Module 1
Welcome to your interactive FEA journey! We are going to explore the theory behind Finite Element Analysis while keeping it highly visual and interactive. 

Ultimately, FEA is about taking a complex structure, breaking it down into smaller, simpler "elements", and figuring out how those elements respond to forces.

Let's start with the most fundamental building block: **The 1D Spring**.


## 1. The Foundation: Hooke's Law
Every continuous material (like a piece of wood or steel) can be thought of as a very complex web of springs. If we understand how one spring behaves, we can build up to complex 3D structures.

The behavior of a single elastic spring is governed by **Hooke's Law**:
$$ F = K \cdot \Delta x $$

Where:
* **$F$** is the Force applied (e.g., pounds, Newtons).
* **$K$** is the Stiffness of the spring. A high $K$ means the spring is very stiff (like steel). A low $K$ means it's stretchy (like a rubber band).
* **$\Delta x$** is the Displacement (how much it stretched or compressed).

Let's visualize this!


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

# Function to draw our spring
def draw_spring(force, stiffness):
    # Calculate displacement: dx = F / K
    displacement = force / stiffness
    
    # Original state
    x_orig = np.linspace(0, 10, 100)
    y_orig = np.sin(x_orig * 2 * np.pi) * 0.5
    
    # Deformed state (stretched or compressed)
    x_def = np.linspace(0, 10 + displacement, 100)
    y_def = np.sin(x_orig * 2 * np.pi) * 0.5
    
    fig, ax = plt.subplots(figsize=(10, 3))
    
    # Draw a wall
    ax.axvline(x=0, color='gray', linewidth=5)
    ax.fill_betweenx([-1, 1], -1, 0, color='lightgray', hatch='//')
    
    # Draw original spring (faintly)
    ax.plot(x_orig, y_orig, color='gray', alpha=0.3, label='Original State', linewidth=2)
    ax.scatter([10], [0], color='gray', s=100, alpha=0.3) # Node
    
    # Draw deformed spring
    ax.plot(x_def, y_def, color='blue', label='Deformed State', linewidth=2)
    ax.scatter([10 + displacement], [0], color='blue', s=100, label='Node') # Node
    
    # Draw Force Arrow
    if force != 0:
        arrow_x = 10 + displacement
        ax.arrow(arrow_x, 0.5, force/20, 0, head_width=0.2, head_length=0.5, fc='red', ec='red', linewidth=2)
        ax.text(arrow_x + force/40, 0.7, f'Force: {force} N', color='red', ha='center')
    
    ax.set_xlim(-1, 20)
    ax.set_ylim(-1.5, 1.5)
    ax.set_title(f"Hooke's Law: F = K * dx\nDisplacement = {displacement:.2f} m")
    ax.axis('off')
    ax.legend()
    plt.show()

# Create interactive sliders
force_slider = widgets.FloatSlider(value=0, min=-50, max=50, step=1, description='Force (F):')
stiffness_slider = widgets.FloatSlider(value=10, min=1, max=30, step=1, description='Stiffness (K):')

# Display interactive plot
widgets.interact(draw_spring, force=force_slider, stiffness=stiffness_slider);


interactive(children=(FloatSlider(value=0.0, description='Force (F):', max=50.0, min=-50.0, step=1.0), FloatSl…

## 2. From Springs to Matrices (The Math)

In FEA, we rarely deal with a single spring. We deal with **nodes** (points) connected by **elements** (springs/trusses).

Let's look at a single spring element connecting Node 1 and Node 2.
* Node 1 has displacement $u_1$ and experiences force $f_1$.
* Node 2 has displacement $u_2$ and experiences force $f_2$.

If we apply Hooke's Law to both nodes simultaneously, we can write it in matrix form:

$$
\begin{bmatrix}
f_1 \\
f_2
\end{bmatrix}
=
K
\begin{bmatrix}
 1 & -1 \\
-1 &  1
\end{bmatrix}
\begin{bmatrix}
u_1 \\
u_2
\end{bmatrix}
$$

This $2 \times 2$ matrix is called the **Local Stiffness Matrix** for a 1D element.

### Coding Exercise: Build the Matrix
Now it's your turn. In the cell below, write a Python function that takes the stiffness $K$ and returns this $2 \times 2$ stiffness matrix using `numpy`.


In [2]:
# EXERCISE: Create the Local Stiffness Matrix
import numpy as np

def create_local_stiffness_matrix(k):
    # TODO: Create a 2x2 numpy array representing the stiffness matrix shown above.
    # Replace the zeros below with the correct formula.
    
    matrix = np.array([
        [0, 0],
        [0, 0]
    ])
    
    return matrix

# Let's test it!
k_example = 500 # Stiffness of 500 N/m
k_matrix = create_local_stiffness_matrix(k_example)
print("Your Stiffness Matrix:")
print(k_matrix)


Your Stiffness Matrix:
[[0 0]
 [0 0]]


### Solution (Click to expand)

In [3]:
# SOLUTION:
def create_local_stiffness_matrix_solution(k):
    matrix = k * np.array([
        [ 1, -1],
        [-1,  1]
    ])
    return matrix


## 3. Global Assembly (Connecting the Dots)
If we have *two* springs connected end-to-end, we have 3 nodes total.

* Spring 1 connects Node 1 and Node 2 (Stiffness $k_1$).
* Spring 2 connects Node 2 and Node 3 (Stiffness $k_2$).

To solve the whole system, we must "assemble" a **Global Stiffness Matrix** that is $3 \times 3$.
We do this by adding the local matrices into the global matrix at the indices corresponding to their node numbers.

$$
K_{global} = 
\begin{bmatrix}
k_1 & -k_1 & 0 \\
-k_1 & k_1 + k_2 & -k_2 \\
0 & -k_2 & k_2
\end{bmatrix}
$$

### Coding Exercise: Global Assembly
Write a function that takes $k_1$ and $k_2$ and builds the $3 \times 3$ global stiffness matrix.


In [4]:
# EXERCISE: Create the Global Stiffness Matrix
def create_global_stiffness_matrix(k1, k2):
    # TODO: Create a 3x3 numpy array
    global_k = np.zeros((3, 3))
    
    # Fill in the matrix
    
    return global_k

# Test it
K_global = create_global_stiffness_matrix(100, 200)
print("Your Global Stiffness Matrix:")
print(K_global)


Your Global Stiffness Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Solution (Click to expand)

In [5]:
# SOLUTION:
def create_global_stiffness_matrix_solution(k1, k2):
    global_k = np.array([
        [ k1,      -k1,        0],
        [-k1,  k1 + k2,      -k2],
        [  0,      -k2,       k2]
    ])
    return global_k


## 4. Solving the System (Boundary Conditions)

We have our Global Equation: 
$$ F_{global} = K_{global} \cdot U_{global} $$

Where $U$ is a vector of displacements. 
If we just try to solve this right now, the matrix is "singular" (it has no unique solution). Physically, this means the springs are floating in space! If we apply a force, they will just fly away infinitely.

We must apply **Boundary Conditions**. Let's "pin" Node 1 to a wall. This means we know the displacement at Node 1 is zero: $u_1 = 0$.

If we apply a known force $F_3$ to Node 3, and no force to Node 2 ($F_2 = 0$), our system looks like this:

$$
\begin{bmatrix}
F_{reaction} \\
0 \\
F_3
\end{bmatrix}
=
\begin{bmatrix}
k_1 & -k_1 & 0 \\
-k_1 & k_1 + k_2 & -k_2 \\
0 & -k_2 & k_2
\end{bmatrix}
\begin{bmatrix}
0 \\
u_2 \\
u_3
\end{bmatrix}
$$

Because $u_1 = 0$, we can cross out the first row and first column to solve for the unknown displacements $u_2$ and $u_3$!

$$
\begin{bmatrix}
0 \\
F_3
\end{bmatrix}
=
\begin{bmatrix}
k_1 + k_2 & -k_2 \\
-k_2 & k_2
\end{bmatrix}
\begin{bmatrix}
u_2 \\
u_3
\end{bmatrix}
$$

Now we just invert the reduced stiffness matrix and multiply it by the force vector to find $u_2$ and $u_3$!


In [6]:
# EXERCISE: Solve for displacements
# We will use numpy's linear algebra solver: np.linalg.solve(A, b)

def solve_system(k1, k2, F3):
    # 1. Build the reduced stiffness matrix (2x2)
    K_reduced = np.array([
        [k1 + k2, -k2],
        [-k2,      k2]
    ])
    
    # 2. Build the force vector (2x1)
    F_reduced = np.array([0, F3])
    
    # 3. Solve for displacements U_reduced = [u2, u3]
    # TODO: Use np.linalg.solve() here
    U_reduced = np.array([0, 0]) 
    
    # Add back u1 = 0
    U_global = np.insert(U_reduced, 0, 0)
    return U_global

# Let's test it: k1=100, k2=200, Force at node 3 = 500
displacements = solve_system(100, 200, 500)
print("Displacements at Nodes [1, 2, 3]:", displacements)


Displacements at Nodes [1, 2, 3]: [0 0 0]


### Solution (Click to expand)

In [7]:
# SOLUTION:
def solve_system_solution(k1, k2, F3):
    K_reduced = np.array([
        [k1 + k2, -k2],
        [-k2,      k2]
    ])
    F_reduced = np.array([0, F3])
    
    U_reduced = np.linalg.solve(K_reduced, F_reduced)
    
    U_global = np.insert(U_reduced, 0, 0)
    return U_global


## 5. Visualizing the Final Solved System
Let's take the code you just wrote and wrap it in an interactive visualizer. 
You can play with the stiffnesses of the two springs and the force applied to the end node, and watch how the system solves itself and deforms!


In [8]:
def visualize_solved_system(k1, k2, F3):
    # Get displacements using our solved function (using the solution function here to ensure it works)
    U = solve_system_solution(k1, k2, F3)
    
    # Original node positions
    nodes_orig = [0, 5, 10]
    # Deformed node positions
    nodes_def = [0, 5 + U[1], 10 + U[2]]
    
    fig, ax = plt.subplots(figsize=(10, 3))
    
    # Wall
    ax.axvline(x=0, color='black', linewidth=3)
    
    # Plot original state
    ax.plot(nodes_orig, [0, 0, 0], 'o-', color='gray', alpha=0.3, label='Original', markersize=10, linewidth=2)
    
    # Plot deformed state
    ax.plot(nodes_def, [0, 0, 0], 'o-', color='blue', label='Deformed', markersize=10, linewidth=3)
    
    # Add Force Arrow at Node 3
    if F3 != 0:
        ax.arrow(nodes_def[2], 0.2, F3/200, 0, head_width=0.1, head_length=0.3, fc='red', ec='red', linewidth=2)
        ax.text(nodes_def[2], 0.4, f'F = {F3}', color='red', ha='center')
        
    ax.set_ylim(-1, 1)
    ax.set_xlim(-1, max(15, nodes_def[2] + 2))
    ax.set_title(f"2-Spring System\nNode 2 Displacement: {U[1]:.2f} | Node 3 Displacement: {U[2]:.2f}")
    ax.axis('off')
    ax.legend()
    plt.show()

widgets.interact(visualize_solved_system, 
                 k1=widgets.FloatSlider(value=100, min=10, max=500, step=10, description='Stiff 1 (k1)'),
                 k2=widgets.FloatSlider(value=200, min=10, max=500, step=10, description='Stiff 2 (k2)'),
                 F3=widgets.FloatSlider(value=500, min=-1000, max=1000, step=50, description='Force (F3)'));


interactive(children=(FloatSlider(value=100.0, description='Stiff 1 (k1)', max=500.0, min=10.0, step=10.0), Fl…